### ISSUE TITLE
Suggestion: show [SOCVFinder] at the start of all auto report messages

### ISSUE THREAD

**Issue by gunr2171** [jdd-software/SOCVFinder#3]
A typical smoke detector message is formatted like this:

>  [ [SmokeDetector](//git.io/vgx7b) ] Bad keyword in body: [How to read some columns from a CSV file with C++?](//stackoverflow.com/questions/10598872) by [Adrian](//stackoverflow.com/u/1394099) on `stackoverflow.com` (..mentions..) […](//metasmoke.erwaysoftware.com/posts/by-url?url=//stackoverflow.com/questions/10598872)

Would it be worth adding that prefix to the bot as well? I'm assuming that most people interact with the bot by reacting to reports auto-announced. It will also help advertise that it's a bot and give a quick way to access the commands.

> [ [SOCVFinder](https://github.com/jdd-software/SOCVFinder) ] [tag:possible-duplicate] [tag:java] [tag:rest] [tag:spring-restcontroller] [tag:spring-rest] [Currency Symbols like €,£ are Corrupted in Spring HTTP.GET](http://stackoverflow.com/questions/37928309)

**Comment by gunr2171** [comment]
Of course, this prefix should not be necessary if the bot is running a command. The person, in that case, already knows that it's a bot.

**Comment by ArcticEcho** [comment]
Why don't we do this with all the bots?

**Comment by gunr2171** [comment]
That is certainly an option.

**Comment by jdd-software** [comment]
Yes nice FR I will include it in next update, thanks
